Explictly do not support Windows, avoid error codes
ttacon/chalk pull request #6
Opened 2019-08-21 03:04 UTC by mkaz

The Windows console does not support the same ANSI character codes, so when they are printed out it ends up looking like gibberish characters.

This PR avoids this by simply returning blank strings for the functions. This removes all color syntax for windows builds only.

Explanation for setting up platform conditional builds is here: 
https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

2019-08-28 20:00 UTC, ttacon requested changes
Awesome, thanks for the PR! A few things to cleanup, overall looking good!

2019-08-28 20:00 UTC, ttacon commented on chalk_windows.go
> +	// return fmt.Sprintf("\u001b[%dm", 30+c.value)
Can we remove this line and all other commented out lines?

2019-08-28 20:00 UTC, ttacon commented on chalk_windows.go
> +var (
Any need to duplicate the `var`s here? What are your thoughts on refactoring these out of both files to their own file to avoid duplication?

2019-08-28 23:55 UTC, mkaz commented on chalk_windows.go
> +	// return fmt.Sprintf("\u001b[%dm", 30+c.value)
Removed :+1:

2019-08-28 23:56 UTC, mkaz commented on chalk_windows.go
> +var (
I created a new file called `vars.go` that both platforms will use.

2019-08-29 13:14 UTC, ttacon reviewed
One more question, otherwise LGTM.

2019-08-29 13:14 UTC, ttacon commented on chalk_windows.go
> +	return &style{textStyle: t}
Forgive me for my lack of Windows knowledge, should this be an empty string as well?

2021-04-14 11:58 UTC, shils approved these changes

2021-04-14 12:00 UTC, shils approved these changes

2023-02-11 00:00 UTC, closed without merging